'use strict';
const APP_VERSION='1.0.1';
const SCHEMA_VERSION=2;
const KEY_STATE='bodymake12_state_v2';
const KEY_BACKUP='bodymake12_state_backup_v2';
const LEGACY_R='bm12_records_v1';
const LEGACY_S='bm12_settings_v1';
let records=[];
let settings={};
let storageHealthy=true;
let installPrompt=null;
let toastTimer=null;
const LIMITS={weight:[20,300],bodyfat:[1,70],kcal:[0,10000],protein:[0,500],fat:[0,300],carbs:[0,1000],steps:[0,100000],cardio:[0,1440],sleep:[0,24],water:[0,20],startWeight:[20,300],goalWeight:[20,300],goalKcal:[0,10000],goalP:[0,500],goalF:[0,300],goalC:[0,1000]};
function isoLocal(d=new Date()){const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
function dateSerial(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(s||'')))return NaN;const[y,m,d]=s.split('-').map(Number),dt=new Date(Date.UTC(y,m-1,d));if(dt.getUTCFullYear()!==y||dt.getUTCMonth()!==m-1||dt.getUTCDate()!==d)return NaN;return Math.floor(dt.getTime()/86400000)}
function isValidDate(s){return Number.isFinite(dateSerial(s))}function diffDays(a,b){return dateSerial(a)-dateSerial(b)}function addDays(s,days){const n=dateSerial(s);if(!Number.isFinite(n))return isoLocal();const d=new Date((n+days)*86400000);return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`}
function val(id){const el=document.getElementById(id);return el?el.value:''}function avg(nums){return nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null}function avgOf(arr,key){const xs=arr.map(r=>r[key]).filter(v=>v!==null&&v!==''&&v!==undefined&&Number.isFinite(Number(v))).map(Number);return xs.length?avg(xs):null}function cleanText(v,max=100){return String(v??'').trim().slice(0,max)}
function finiteOrNull(v,min,max){if(v===null||v===''||v===undefined)return null;const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)return null;return n}
function validInRange(id,label,min,max,required=false){const raw=val(id);if(raw===''){if(required){toast(`${label}を入力してください`);document.getElementById(id)?.focus();return{ok:false,value:null}}return{ok:true,value:null}}const n=Number(raw);if(!Number.isFinite(n)||n<min||n>max){toast(`${label}は${min}〜${max}の範囲で入力してください`);document.getElementById(id)?.focus();return{ok:false,value:null}}return{ok:true,value:n}}
function sanitizeTraining(v){const allowed=new Set(['胸','背中','肩','脚','腕','腹','休み','その他']);let arr=String(v||'').split(/[・,、\/]/).map(x=>x.trim()).filter(x=>allowed.has(x));arr=[...new Set(arr)];if(arr.includes('休み')&&arr.length>1)arr=arr.filter(x=>x!=='休み');return arr.join('・')}
function sanitizeRecord(o){if(!o||!isValidDate(o.date))return null;return{date:o.date,weight:finiteOrNull(o.weight,...LIMITS.weight),bodyfat:finiteOrNull(o.bodyfat,...LIMITS.bodyfat),kcal:finiteOrNull(o.kcal,...LIMITS.kcal),protein:finiteOrNull(o.protein,...LIMITS.protein),fat:finiteOrNull(o.fat,...LIMITS.fat),carbs:finiteOrNull(o.carbs,...LIMITS.carbs),steps:finiteOrNull(o.steps,...LIMITS.steps),cardio:finiteOrNull(o.cardio,...LIMITS.cardio),sleep:finiteOrNull(o.sleep,...LIMITS.sleep),water:finiteOrNull(o.water,...LIMITS.water),training:sanitizeTraining(o.training),condition:['1','2','3','4','5'].includes(String(o.condition||''))?String(o.condition):'',memo:cleanText(o.memo,1000)}}
function sanitizeSettings(o={}){const start=isValidDate(o.startDate)?o.startDate:isoLocal();let goal=isValidDate(o.goalDate)?o.goalDate:addDays(start,83);if(diffDays(goal,start)<0)goal=addDays(start,83);return{clientName:cleanText(o.clientName,60),trainerName:cleanText(o.trainerName,60),startDate:start,goalDate:goal,startWeight:finiteOrNull(o.startWeight,...LIMITS.startWeight),goalWeight:finiteOrNull(o.goalWeight,...LIMITS.goalWeight),goalKcal:finiteOrNull(o.goalKcal,...LIMITS.goalKcal),goalP:finiteOrNull(o.goalP,...LIMITS.goalP),goalF:finiteOrNull(o.goalF,...LIMITS.goalF),goalC:finiteOrNull(o.goalC,...LIMITS.goalC)}}
function normalizeRecords(arr){const map=new Map();(Array.isArray(arr)?arr:[]).forEach(x=>{const r=sanitizeRecord(x);if(r)map.set(r.date,r)});return[...map.values()].sort((a,b)=>a.date.localeCompare(b.date))}function safeParse(raw){try{return raw?JSON.parse(raw):null}catch{return null}}function storageGet(k){try{return localStorage.getItem(k)}catch{storageHealthy=false;return null}}function storageSet(k,v){try{localStorage.setItem(k,v);return true}catch{storageHealthy=false;showStorageWarning();return false}}function storageRemove(k){try{localStorage.removeItem(k)}catch{storageHealthy=false;showStorageWarning()}}function showStorageWarning(){document.getElementById('storageWarning')?.classList.add('show')}function statePayload(){return{schemaVersion:SCHEMA_VERSION,appVersion:APP_VERSION,updatedAt:new Date().toISOString(),settings,records}}
function loadState(){storageHealthy=true;let source='new',state=safeParse(storageGet(KEY_STATE));if(!state||!Array.isArray(state.records)||typeof state.settings!=='object'){const backup=safeParse(storageGet(KEY_BACKUP));if(backup&&Array.isArray(backup.records)&&typeof backup.settings==='object'){state=backup;source='backup'}}if(!state||!Array.isArray(state.records)||typeof state.settings!=='object'){const legacyR=safeParse(storageGet(LEGACY_R)),legacyS=safeParse(storageGet(LEGACY_S));if(Array.isArray(legacyR)||legacyS){state={records:Array.isArray(legacyR)?legacyR:[],settings:legacyS||{}};source='legacy'}}if(!state)state={records:[],settings:{}};records=normalizeRecords(state.records);settings=sanitizeSettings(state.settings);if(source!=='new')persistState({skipBackup:true});if(source==='backup')setTimeout(()=>toast('端末バックアップからデータを復旧しました'),200);if(!storageHealthy)showStorageWarning()}
function persistState({skipBackup=false}={}){const next=JSON.stringify(statePayload()),current=storageGet(KEY_STATE);if(!skipBackup&&current&&safeParse(current))storageSet(KEY_BACKUP,current);const ok=storageSet(KEY_STATE,next);if(ok){storageRemove(LEGACY_R);storageRemove(LEGACY_S)}return ok}
function toast(msg='保存しました'){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}function selectedTraining(){return[...document.querySelectorAll('#trainingGroup input:checked')].map(x=>x.value).join('・')}function setTraining(value=''){const selected=sanitizeTraining(value).split('・').filter(Boolean);document.querySelectorAll('#trainingGroup input').forEach(x=>x.checked=selected.includes(x.value))}
function setupTrainingExclusivity(){document.getElementById('trainingGroup')?.addEventListener('change',e=>{const target=e.target;if(!(target instanceof HTMLInputElement)||target.type!=='checkbox')return;const rest=document.querySelector('#trainingGroup input[value="休み"]');if(target.value==='休み'&&target.checked){document.querySelectorAll('#trainingGroup input').forEach(x=>{if(x!==target)x.checked=false})}else if(target.checked&&rest)rest.checked=false})}function setToday(){document.getElementById('date').value=isoLocal();loadDate()}
function saveRecord(){const date=val('date');if(!isValidDate(date)){toast('正しい日付を入力してください');return}if(diffDays(date,isoLocal())>0){toast('未来の日付は記録できません');return}const defs=[['weight','体重',20,300],['bodyfat','体脂肪率',1,70],['kcal','摂取カロリー',0,10000],['protein','P',0,500],['fat','F',0,300],['carbs','C',0,1000],['steps','歩数',0,100000],['cardio','有酸素',0,1440],['sleep','睡眠',0,24],['water','水分',0,20]],values={};for(const[id,label,min,max]of defs){const r=validInRange(id,label,min,max);if(!r.ok)return;values[id]=r.value}const r=sanitizeRecord({date,...values,training:selectedTraining(),condition:val('condition'),memo:val('memo')});if(!r){toast('入力内容を確認してください');return}records=records.filter(x=>x.date!==date);records.push(r);records.sort((a,b)=>a.date.localeCompare(b.date));if(settings.startWeight==null&&r.weight!=null)settings.startWeight=r.weight;persistState();renderAll();toast(storageHealthy?'保存しました':'一時保存しました')}
function loadDate(){const r=records.find(x=>x.date===val('date'))||{};['weight','bodyfat','kcal','protein','fat','carbs','steps','cardio','sleep','water','condition','memo'].forEach(k=>{const el=document.getElementById(k);if(el)el.value=r[k]??''});setTraining(r.training||'')}